export type AgentRefusalStyle = "polite_redirect" | "polite_decline";

export type AgentUnknownIntentPolicy = "allow" | "clarify_or_refuse";

export type AgentCapabilityContract = {
  agentName: string;
  displayName: string;
  role: string;
  description: string;
  strictBoundary: boolean;
  unknownIntentPolicy: AgentUnknownIntentPolicy;
  allowedDomains: string[];
  deniedDomains: string[];
  allowedKeywords: string[];
  deniedKeywords: string[];
  softAllowedKeywords: string[];
  safeSmallTalkKeywords: string[];
  primarySkills: string[];
  fallbackAgents: string[];
  refusalStyle: AgentRefusalStyle;
  refusalMessage: string;
  unknownIntentMessage: string;
};

export const agentCapabilityContracts: AgentCapabilityContract[] = [
  {
    agentName: "design-agent",
    displayName: "Design Agent",
    role: "Creative marketing and copywriting specialist",
    description:
      "Handles creative marketing copy, ad copy, campaign wording, branding ideas, captions, and short promotional text.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "copywriting",
      "advertising",
      "marketing",
      "caption",
      "branding",
      "campaign",
      "creative writing",
      "promotional text",
      "product message",
      "social media content",
      "sales wording",
    ],
    deniedDomains: [
      "backend coding",
      "frontend coding",
      "database migration",
      "system debugging",
      "devops",
      "server configuration",
      "networking",
      "legal advice",
      "financial advice",
      "medical advice",
      "security exploitation",
      "data extraction",
      "credential handling",
    ],
    allowedKeywords: [
      "caption",
      "copy",
      "copywriting",
      "ad copy",
      "iklan",
      "promosi",
      "kalimat promosi",
      "campaign",
      "kampanye",
      "brand",
      "branding",
      "headline",
      "tagline",
      "slogan",
      "konten",
      "social media",
      "instagram",
      "tiktok",
      "produk",
      "jualan",
      "marketing",
      "market",
      "audience",
      "target audience",
      "landing page copy",
      "cta",
      "call to action",
      "hook",
      "benefit",
      "creative",
      "ide promosi",
      "ide konten",
      "naskah iklan",
      "nama produk",
      "deskripsi produk",
      "copy ads",
    ],
    deniedKeywords: [
      "debug",
      "debugging",
      "error code",
      "typescript error",
      "compile error",
      "runtime error",
      "stack trace",
      "prisma",
      "migration",
      "database",
      "sqlite",
      "postgres",
      "mysql",
      "mongodb",
      "sql",
      "query",
      "schema",
      "seed script",
      "express route",
      "api route",
      "backend",
      "frontend",
      "react component",
      "tsx",
      "jsx",
      "css bug",
      "server error",
      "npm error",
      "vite error",
      "node error",
      "websocket",
      "socket.io",
      "docker",
      "nginx",
      "reverse proxy",
      "deployment",
      "server setup",
      "env error",
      "token exploit",
      "hack",
      "exploit",
      "bypass",
      "credential",
      "password",
      "api key leak",
      "medical",
      "diagnosis",
      "legal",
      "kontrak hukum",
      "financial",
      "investasi",
      "trading signal",
    ],
    softAllowedKeywords: [
      "buatkan",
      "buat",
      "bikin",
      "tolong buat",
      "tulis",
      "generate",
      "create",
      "rekomendasi kata",
      "kalimat",
      "singkat",
      "pendek",
      "simple",
      "jelas",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "pagi",
      "siang",
      "sore",
      "malam",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: ["generate_ad_copy"],
    fallbackAgents: ["writer-agent", "code-agent", "research-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada copywriting, iklan, caption, branding, dan ide promosi. Untuk request di luar area itu, lebih tepat arahkan ke agent yang sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini sesuai scope @design-agent. Aku fokus pada copywriting, iklan, caption, branding, dan ide promosi. Kalau request ini terkait teknis, riset, atau hal lain di luar creative marketing, coba arahkan ke agent yang lebih tepat seperti @code-agent, @research-agent, atau @writer-agent.",
  },
  {
    agentName: "writer-agent",
    displayName: "Writer Agent",
    role: "Long-form and structured writing specialist",
    description:
      "Handles articles, summaries, documentation drafts, emails, scripts, and structured writing tasks.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "writing",
      "article",
      "summary",
      "documentation",
      "email",
      "script",
      "story outline",
      "proposal",
      "content writing",
      "editing",
      "rewriting",
    ],
    deniedDomains: [
      "code debugging",
      "database migration",
      "server configuration",
      "security exploitation",
      "financial advice",
      "medical advice",
      "legal advice",
    ],
    allowedKeywords: [
      "artikel",
      "article",
      "summary",
      "summarize",
      "ringkas",
      "email",
      "draft",
      "proposal",
      "script",
      "narasi",
      "dokumen",
      "documentation",
      "tulis",
      "rewrite",
      "paraphrase",
      "edit tulisan",
      "perbaiki kalimat",
      "struktur tulisan",
      "outline",
      "blog",
      "caption panjang",
      "copy panjang",
    ],
    deniedKeywords: [
      "debug",
      "prisma",
      "migration",
      "sql",
      "typescript",
      "react",
      "node",
      "api route",
      "server config",
      "exploit",
      "hack",
      "diagnosis",
      "kontrak hukum",
      "investasi",
    ],
    softAllowedKeywords: [
      "buatkan",
      "buat",
      "bikin",
      "tolong",
      "tulis",
      "generate",
      "create",
      "perbaiki",
      "rapikan",
      "jelaskan",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: [],
    fallbackAgents: ["design-agent", "research-agent", "code-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada penulisan, rewriting, ringkasan, email, dokumentasi, dan penyusunan konten. Untuk coding, debugging, atau hal legal/medis/finansial, gunakan agent yang lebih sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini termasuk scope @writer-agent. Aku fokus pada penulisan, ringkasan, email, dokumentasi, dan penyusunan konten. Kalau ini teknis atau perlu riset khusus, coba arahkan ke @code-agent atau @research-agent.",
  },
  {
    agentName: "code-agent",
    displayName: "Code Agent",
    role: "Software engineering and debugging specialist",
    description:
      "Handles code review, debugging, implementation planning, refactoring, backend/frontend development, and technical troubleshooting.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "coding",
      "debugging",
      "software engineering",
      "typescript",
      "node.js",
      "react",
      "prisma",
      "database",
      "api",
      "architecture",
      "refactor",
      "devops troubleshooting",
    ],
    deniedDomains: [
      "creative advertising",
      "visual generation",
      "medical advice",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "debug",
      "error",
      "bug",
      "typescript",
      "javascript",
      "react",
      "vite",
      "node",
      "express",
      "prisma",
      "database",
      "migration",
      "schema",
      "api",
      "route",
      "endpoint",
      "component",
      "function",
      "refactor",
      "code",
      "compile",
      "npm",
      "package",
      "backend",
      "frontend",
      "websocket",
      "socket",
      "server",
      "env",
      "docker",
      "nginx",
      "deployment",
      "terminal",
      "stack trace",
    ],
    deniedKeywords: [
      "caption iklan",
      "tagline",
      "slogan promosi",
      "visual prompt",
      "medical",
      "diagnosis",
      "legal advice",
      "financial advice",
      "exploit",
      "hack",
      "bypass",
    ],
    softAllowedKeywords: [
      "tolong",
      "bantu",
      "fix",
      "perbaiki",
      "buatkan",
      "implement",
      "setup",
      "install",
      "jalankan",
      "cek",
      "review",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: [],
    fallbackAgents: ["research-agent", "writer-agent", "design-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada coding, debugging, arsitektur, dan implementasi teknis. Untuk copywriting, branding, atau visual, gunakan agent yang lebih sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini termasuk scope @code-agent. Aku fokus pada coding, debugging, arsitektur, dan troubleshooting teknis. Kalau request ini kreatif, riset, atau writing, coba arahkan ke agent yang lebih tepat.",
  },
  {
    agentName: "research-agent",
    displayName: "Research Agent",
    role: "Research and information synthesis specialist",
    description:
      "Handles research, source gathering, comparison, summarization, and structured findings.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "research",
      "source gathering",
      "comparison",
      "analysis",
      "summary",
      "market research",
      "technical research",
      "documentation research",
      "trend analysis",
    ],
    deniedDomains: [
      "direct code implementation",
      "medical diagnosis",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "research",
      "riset",
      "cari info",
      "cari data",
      "bandingkan",
      "sumber",
      "referensi",
      "analisis",
      "summary",
      "compare",
      "latest",
      "terbaru",
      "tren",
      "trend",
      "market",
      "benchmark",
      "studi",
      "literatur",
      "kumpulkan",
      "validasi informasi",
    ],
    deniedKeywords: [
      "buat kode full",
      "implement full code",
      "hack",
      "exploit",
      "diagnosis",
      "nasihat hukum",
      "investasi pasti",
      "trading signal",
    ],
    softAllowedKeywords: [
      "tolong",
      "bantu",
      "jelaskan",
      "cari",
      "buatkan",
      "ringkas",
      "apa itu",
      "bagaimana",
      "kenapa",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: [],
    fallbackAgents: ["writer-agent", "code-agent", "design-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada riset, perbandingan, validasi informasi, dan sintesis temuan. Untuk implementasi kode atau copywriting final, gunakan agent yang lebih sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini termasuk scope @research-agent. Aku fokus pada riset, sumber, perbandingan, dan analisis informasi. Kalau request ini implementasi atau creative output, coba arahkan ke agent yang lebih tepat.",
  },
  {
    agentName: "image-agent",
    displayName: "Image Agent",
    role: "Visual and media generation specialist",
    description:
      "Handles image prompt design, visual concepts, media generation planning, and creative visual direction.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "image prompt",
      "visual concept",
      "media generation",
      "illustration idea",
      "visual direction",
      "photo concept",
      "design reference",
      "poster concept",
      "thumbnail concept",
    ],
    deniedDomains: [
      "backend coding",
      "database migration",
      "legal advice",
      "financial advice",
      "medical advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "image",
      "gambar",
      "visual",
      "prompt gambar",
      "ilustrasi",
      "foto",
      "render",
      "poster",
      "thumbnail",
      "media",
      "desain visual",
      "komposisi",
      "style visual",
      "warna",
      "moodboard",
      "konsep visual",
      "generate image",
    ],
    deniedKeywords: [
      "prisma",
      "migration",
      "debug kode",
      "sql",
      "backend",
      "api route",
      "legal",
      "medical",
      "financial",
      "exploit",
      "hack",
    ],
    softAllowedKeywords: [
      "buatkan",
      "buat",
      "bikin",
      "tolong",
      "generate",
      "desain",
      "konsep",
      "ide",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: [],
    fallbackAgents: ["design-agent", "writer-agent", "code-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada visual, image prompt, konsep media, dan arahan kreatif visual. Untuk coding, debugging, atau riset teknis, gunakan agent yang lebih sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini termasuk scope @image-agent. Aku fokus pada visual, image prompt, dan konsep media. Kalau request ini teknis atau writing, coba arahkan ke agent yang lebih tepat.",
  },
  {
    agentName: "qa-agent",
    displayName: "QA Agent",
    role: "Testing and quality assurance specialist",
    description:
      "Handles test planning, QA checklist, bug reproduction steps, validation, and regression testing.",
    strictBoundary: true,
    unknownIntentPolicy: "clarify_or_refuse",
    allowedDomains: [
      "testing",
      "qa",
      "quality assurance",
      "test case",
      "bug reproduction",
      "regression",
      "validation",
      "checklist",
      "acceptance criteria",
    ],
    deniedDomains: [
      "creative marketing",
      "medical advice",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "test",
      "testing",
      "qa",
      "bug",
      "regression",
      "checklist",
      "validasi",
      "validate",
      "reproduce",
      "scenario",
      "skenario",
      "edge case",
      "acceptance criteria",
      "hasil test",
      "case",
      "quality",
    ],
    deniedKeywords: [
      "caption",
      "tagline",
      "slogan",
      "medical",
      "legal",
      "financial",
      "exploit",
      "hack",
      "campaign copy",
    ],
    softAllowedKeywords: [
      "buatkan",
      "buat",
      "tolong",
      "cek",
      "review",
      "validasi",
      "test",
      "uji",
    ],
    safeSmallTalkKeywords: [
      "halo",
      "hai",
      "hello",
      "hi",
      "terima kasih",
      "thanks",
      "makasih",
      "siapa kamu",
      "kamu bisa apa",
    ],
    primarySkills: [],
    fallbackAgents: ["code-agent", "research-agent", "writer-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada testing, QA, validasi, checklist, dan bug reproduction. Untuk copywriting atau implementasi fitur, gunakan agent yang lebih sesuai.",
    unknownIntentMessage:
      "Aku belum bisa memastikan request ini termasuk scope @qa-agent. Aku fokus pada testing, QA, validasi, dan bug reproduction. Kalau request ini implementasi atau creative output, coba arahkan ke agent yang lebih tepat.",
  },
];

export function findAgentCapabilityContract(agentName: string) {
  return (
    agentCapabilityContracts.find(
      (contract) => contract.agentName === agentName
    ) || null
  );
}

export function listAgentCapabilityContracts() {
  return agentCapabilityContracts;
}