export type AgentRefusalStyle = "polite_redirect" | "polite_decline";

export type AgentCapabilityContract = {
  agentName: string;
  displayName: string;
  role: string;
  description: string;
  allowedDomains: string[];
  deniedDomains: string[];
  allowedKeywords: string[];
  deniedKeywords: string[];
  primarySkills: string[];
  fallbackAgents: string[];
  refusalStyle: AgentRefusalStyle;
  refusalMessage: string;
};

export const agentCapabilityContracts: AgentCapabilityContract[] = [
  {
    agentName: "design-agent",
    displayName: "Design Agent",
    role: "Creative marketing and copywriting specialist",
    description:
      "Handles creative marketing copy, ad copy, campaign wording, branding ideas, captions, and short promotional text.",
    allowedDomains: [
      "copywriting",
      "advertising",
      "marketing",
      "caption",
      "branding",
      "campaign",
      "creative writing",
      "promotional text",
      "product message",
    ],
    deniedDomains: [
      "backend coding",
      "frontend coding",
      "database migration",
      "system debugging",
      "legal advice",
      "financial advice",
      "medical advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "caption",
      "copy",
      "ad copy",
      "iklan",
      "promosi",
      "kalimat promosi",
      "campaign",
      "brand",
      "branding",
      "headline",
      "tagline",
      "slogan",
      "konten",
      "social media",
      "instagram",
      "tiktok",
      "produk",
      "jualan",
      "marketing",
    ],
    deniedKeywords: [
      "debug",
      "error code",
      "typescript error",
      "prisma",
      "migration",
      "database",
      "sql",
      "express route",
      "react component",
      "css bug",
      "server error",
      "token exploit",
      "hack",
      "medical",
      "legal",
      "financial",
    ],
    primarySkills: ["generate_ad_copy"],
    fallbackAgents: ["writer-agent", "code-agent", "research-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada copywriting, iklan, caption, branding, dan ide promosi. Untuk request di luar area itu, lebih tepat arahkan ke agent yang sesuai.",
  },
  {
    agentName: "writer-agent",
    displayName: "Writer Agent",
    role: "Long-form and structured writing specialist",
    description:
      "Handles articles, summaries, documentation drafts, emails, scripts, and structured writing tasks.",
    allowedDomains: [
      "writing",
      "article",
      "summary",
      "documentation",
      "email",
      "script",
      "story outline",
      "proposal",
      "content writing",
    ],
    deniedDomains: [
      "code debugging",
      "database migration",
      "security exploitation",
      "financial advice",
      "medical advice",
      "legal advice",
    ],
    allowedKeywords: [
      "artikel",
      "summary",
      "ringkas",
      "email",
      "draft",
      "proposal",
      "script",
      "narasi",
      "dokumen",
      "documentation",
      "tulis",
      "rewrite",
      "paraphrase",
    ],
    deniedKeywords: [
      "debug",
      "prisma",
      "migration",
      "sql",
      "exploit",
      "hack",
      "diagnosis",
      "kontrak hukum",
    ],
    primarySkills: [],
    fallbackAgents: ["design-agent", "research-agent", "code-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada penulisan dan penyusunan konten. Untuk coding, riset teknis mendalam, atau hal legal/medis/finansial, gunakan agent yang lebih sesuai.",
  },
  {
    agentName: "code-agent",
    displayName: "Code Agent",
    role: "Software engineering and debugging specialist",
    description:
      "Handles code review, debugging, implementation planning, refactoring, backend/frontend development, and technical troubleshooting.",
    allowedDomains: [
      "coding",
      "debugging",
      "software engineering",
      "typescript",
      "node.js",
      "react",
      "prisma",
      "database",
      "api",
      "architecture",
      "refactor",
    ],
    deniedDomains: [
      "creative advertising",
      "visual generation",
      "medical advice",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "debug",
      "error",
      "typescript",
      "react",
      "node",
      "express",
      "prisma",
      "database",
      "migration",
      "api",
      "route",
      "component",
      "function",
      "refactor",
      "code",
      "bug",
      "compile",
      "npm",
      "vite",
    ],
    deniedKeywords: [
      "caption iklan",
      "tagline",
      "visual prompt",
      "medical",
      "legal",
      "financial",
      "exploit",
      "hack",
    ],
    primarySkills: [],
    fallbackAgents: ["research-agent", "writer-agent", "design-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada coding, debugging, arsitektur, dan implementasi teknis. Untuk copywriting atau visual, gunakan agent yang lebih sesuai.",
  },
  {
    agentName: "research-agent",
    displayName: "Research Agent",
    role: "Research and information synthesis specialist",
    description:
      "Handles research, source gathering, comparison, summarization, and structured findings.",
    allowedDomains: [
      "research",
      "source gathering",
      "comparison",
      "analysis",
      "summary",
      "market research",
      "technical research",
      "documentation research",
    ],
    deniedDomains: [
      "direct code implementation",
      "medical diagnosis",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "research",
      "riset",
      "cari info",
      "bandingkan",
      "sumber",
      "referensi",
      "analisis",
      "summary",
      "compare",
      "latest",
      "tren",
      "market",
    ],
    deniedKeywords: [
      "buat kode full",
      "hack",
      "exploit",
      "diagnosis",
      "nasihat hukum",
      "investasi pasti",
    ],
    primarySkills: [],
    fallbackAgents: ["writer-agent", "code-agent", "design-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada riset, perbandingan, dan sintesis informasi. Untuk implementasi kode atau copywriting final, gunakan agent yang lebih sesuai.",
  },
  {
    agentName: "image-agent",
    displayName: "Image Agent",
    role: "Visual and media generation specialist",
    description:
      "Handles image prompt design, visual concepts, media generation planning, and creative visual direction.",
    allowedDomains: [
      "image prompt",
      "visual concept",
      "media generation",
      "illustration idea",
      "visual direction",
      "photo concept",
      "design reference",
    ],
    deniedDomains: [
      "backend coding",
      "database migration",
      "legal advice",
      "financial advice",
      "medical advice",
    ],
    allowedKeywords: [
      "image",
      "gambar",
      "visual",
      "prompt gambar",
      "ilustrasi",
      "foto",
      "render",
      "poster",
      "thumbnail",
      "media",
      "desain visual",
    ],
    deniedKeywords: [
      "prisma",
      "migration",
      "debug kode",
      "sql",
      "legal",
      "medical",
      "financial",
    ],
    primarySkills: [],
    fallbackAgents: ["design-agent", "writer-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada visual, image prompt, dan konsep media. Untuk coding atau riset teknis, gunakan agent yang lebih sesuai.",
  },
  {
    agentName: "qa-agent",
    displayName: "QA Agent",
    role: "Testing and quality assurance specialist",
    description:
      "Handles test planning, QA checklist, bug reproduction steps, validation, and regression testing.",
    allowedDomains: [
      "testing",
      "qa",
      "quality assurance",
      "test case",
      "bug reproduction",
      "regression",
      "validation",
      "checklist",
    ],
    deniedDomains: [
      "creative marketing",
      "medical advice",
      "legal advice",
      "financial advice",
      "security exploitation",
    ],
    allowedKeywords: [
      "test",
      "qa",
      "bug",
      "regression",
      "checklist",
      "validasi",
      "reproduce",
      "scenario",
      "edge case",
      "acceptance criteria",
    ],
    deniedKeywords: [
      "caption",
      "tagline",
      "medical",
      "legal",
      "financial",
      "exploit",
      "hack",
    ],
    primarySkills: [],
    fallbackAgents: ["code-agent", "research-agent"],
    refusalStyle: "polite_redirect",
    refusalMessage:
      "Aku fokus pada testing, QA, validasi, dan bug reproduction. Untuk copywriting atau implementasi fitur, gunakan agent yang lebih sesuai.",
  },
];

export function findAgentCapabilityContract(agentName: string) {
  return (
    agentCapabilityContracts.find(
      (contract) => contract.agentName === agentName
    ) || null
  );
}

export function listAgentCapabilityContracts() {
  return agentCapabilityContracts;
}